name: Java CI with Gradle

on:
  push:
    branches-ignore:
      gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache gradle files
      uses: actions/cache@v1
      env:
        cache-name: cache-gradle-files
      with:
        path: ~/.gradle/caches
        key: gradle-${{ env.cache-name }}-${{ hashFiles('build.gradle') }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Check spotless
      run: ./gradlew spotlessCheck
    - name: Run tests
      run: ./gradlew clean test
